### ISSUE TITLE
can't run server

### ISSUE THREAD

**Issue by justin-hackin** [WMeldon/ember-cli-todos#10]
I tried installing this app after bower and npm installs and when i run ember server it spits out this:

```
Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at rimraf (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:57:13)
    at lib$rsvp$node$$tryApply (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1467:11)
    at lib$rsvp$node$$handleValueInput (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1567:20)
    at fn (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1555:18)
    at /home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:100:14
    at lib$rsvp$$internal$$tryCatch (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
^CCleanup error.
Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var g = new Glob(pattern, options, cb)
  return g.sync ? g.found : g
} has no method 'hasMagic'
    at Function.rimrafSync [as sync] (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/node_modules/rimraf/rimraf.js:262:13)
    at ConfigLoader.CachingWriter.cleanup (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli-caching-writer/index.js:114:10)
    at cleanupTree (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:128:19)
    at /home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
    at Object.lib$rsvp$asap$$flush [as _onImmediate] (/home/cosmo/Web/ember-cli-todos/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
    at processImmediate [as _immediateCallback] (timers.js:354:15)

```

**Comment by stefanpenner** [comment]
Ya. Bug in glob trolled everyone. I'll try to finish my upgrade branch tomorrow and get it merged in. Sorry it's been lagging

**Comment by gboysko** [comment]
Any updates on this?

**Comment by stefanpenner** [comment]
this branch works, although i still need port some tests. 
https://github.com/WMeldon/ember-cli-todos/pull/8

**Comment by stefanpenner** [comment]
master is updated
